#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run from the pipeline root whatever the caller's directory, so .env and worker/ resolve.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[[ -f "$ENV_FILE" ]] && chmod 600 "$ENV_FILE"

TOTAL_STAGES=11
DEFAULT_REPO="gabrielvuksani/nearpost-pipeline"

# wrangler from worker/, pinned by worker/package-lock.json.
wrangler() { (cd worker && npx --no-install wrangler "$@"); }

# http_status METHOD URL: the URL goes to curl through stdin (-K -), so a key embedded in it
# never appears in argv or `ps`. Prints the status code; curl's own errors still reach stderr.
http_status() {
  printf 'url = "%s"\n' "$2" | curl -sS -X "$1" -o /dev/null -w '%{http_code}' --max-time 20 -K - || true
}

# retry_or_skip "what": after a failed check, re-ask (return 0) or give up on it (return 1).
retry_or_skip() {
  warn "$1 did not check out."
  if confirm "Try entering it again?"; then return 0; fi
  SKIPPED+=("$1"); return 1
}

banner "Nearpost recorder: go live"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: tools and repository"
missing=()
for tool in gh node npm uv curl; do command -v "$tool" >/dev/null 2>&1 || missing+=("$tool"); done
if (( ${#missing[@]} )); then warn "Install these first: ${missing[*]}"; exit 1; fi
if ! gh auth status >/dev/null 2>&1; then warn "Run 'gh auth login' first, then re-run this wizard."; exit 1; fi
say "The recorder runs in a GitHub repository that must already exist and contain this pipeline."
ask NEARPOST_GITHUB_REPO "GitHub repo (owner/name, default $DEFAULT_REPO):"
NEARPOST_GITHUB_REPO="${NEARPOST_GITHUB_REPO:-$DEFAULT_REPO}"
if ! repo_check=$(gh repo view "$NEARPOST_GITHUB_REPO" --json nameWithOwner --jq .nameWithOwner 2>&1); then
  warn "Can't see $NEARPOST_GITHUB_REPO: $repo_check"
  say "Create and push the repo first (see README 'Go-live checklist'), then re-run."
  exit 1
fi
export GH_REPO="$NEARPOST_GITHUB_REPO"   # gh secret/workflow commands below target this repo
write_env NEARPOST_GITHUB_REPO "$NEARPOST_GITHUB_REPO"
if ! grep -q "^GITHUB_REPO = \"$NEARPOST_GITHUB_REPO\"" worker/wrangler.toml; then
  sed -i.bak "s|^GITHUB_REPO = \".*\"|GITHUB_REPO = \"$NEARPOST_GITHUB_REPO\"|" worker/wrangler.toml && rm worker/wrangler.toml.bak
  say "Pointed the Worker at $NEARPOST_GITHUB_REPO in worker/wrangler.toml."
fi
say "Installing pinned dependencies (Python and the Worker's wrangler)…"
uv sync --locked --no-dev -q
(cd worker && npm ci --no-audit --no-fund)
pause "Tools ready. Continue?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The Odds API: free key"
say "The market line comes from The Odds API's free Starter plan (500 credits a month)."
open_url "https://the-odds-api.com/#get-access"
step "Under 'Starter' (free), click Start, enter your email, and confirm."
step "Copy the API key from the email they send."
while true; do
  ask_secret ODDS_API_KEY "Paste the Odds API key:"
  # /v4/sports costs no credits, so checking the key is free.
  code=$(http_status GET "https://api.the-odds-api.com/v4/sports/?apiKey=${ODDS_API_KEY}")
  if [[ "$code" == "200" ]]; then say "Key accepted (no credits used)."; break; fi
  say "The Odds API answered HTTP ${code:-no response}."
  retry_or_skip "ODDS_API_KEY" || break
done
write_env ODDS_API_KEY "$ODDS_API_KEY"
set_secret ODDS_API_KEY "$ODDS_API_KEY"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "healthchecks.io: ping key"
say "Every run reports here, and missing or failed runs alert your phone."
open_url "https://healthchecks.io/accounts/signup/"
step "Sign up (free Hobbyist plan) and create a project called Nearpost."
step "Open the project → Settings → 'Ping key' → Create, then copy the key."
while true; do
  ask_secret HEALTHCHECKS_PING_KEY "Paste the project ping key:"
  # A /log ping creates the nearpost-daily check without marking it up or down.
  code=$(http_status POST "https://hc-ping.com/${HEALTHCHECKS_PING_KEY}/nearpost-daily/log?create=1")
  if [[ "$code" == "200" || "$code" == "201" ]]; then say "Ping key works (created the nearpost-daily check)."; break; fi
  say "healthchecks.io answered HTTP ${code:-no response}."
  retry_or_skip "HEALTHCHECKS_PING_KEY" || break
done
write_env HEALTHCHECKS_PING_KEY "$HEALTHCHECKS_PING_KEY"
set_secret HEALTHCHECKS_PING_KEY "$HEALTHCHECKS_PING_KEY"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: log in and enable R2"
whoami=$(wrangler whoami 2>&1 || true)
if grep -qiE "not (authenticated|logged in)" <<<"$whoami"; then
  say "Logging wrangler in to Cloudflare (a browser window will ask you to allow it)."
  wrangler login
  whoami=$(wrangler whoami 2>&1 || true)
fi
printf '%s\n' "$whoami" | sed 's/^/    /'
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "If R2 isn't enabled yet, enable it. Cloudflare may ask for a payment method even"
step "on the free tier (10 GB); the recorder stays far below that (~0.5 GB a season)."
step "Copy your Account ID (shown above, and under R2 → Account details)."
while true; do
  ask R2_ACCOUNT_ID "Cloudflare Account ID:"
  [[ "$R2_ACCOUNT_ID" =~ ^[0-9a-f]{32}$ ]] && break
  retry_or_skip "R2_ACCOUNT_ID (expected 32 hex characters)" || break
done
write_env R2_ACCOUNT_ID "$R2_ACCOUNT_ID"
set_secret R2_ACCOUNT_ID "$R2_ACCOUNT_ID"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "R2: bucket and write-once locks"
ask R2_BUCKET "Bucket name (default nearpost-recorder):"
R2_BUCKET="${R2_BUCKET:-nearpost-recorder}"
write_env R2_BUCKET "$R2_BUCKET"
set_secret R2_BUCKET "$R2_BUCKET"
if bucket_info=$(wrangler r2 bucket info "$R2_BUCKET" 2>&1); then
  say "Bucket $R2_BUCKET already exists."
elif confirm "Create the private R2 bucket $R2_BUCKET?"; then
  wrangler r2 bucket create "$R2_BUCKET"
else
  note "$bucket_info"; SKIPPED+=("R2 bucket $R2_BUCKET")
fi
locks=$(wrangler r2 bucket lock list "$R2_BUCKET" 2>&1 || true)
say "Bucket locks make evidence write-once: nothing under ledger/blocks/ can ever be"
say "deleted or overwritten by the pipeline's credentials; snapshots/ are kept 400 days."
warn "These retentions apply to every object written under those prefixes."
if grep -q "ledger-blocks" <<<"$locks"; then
  say "Lock rules already present."
elif confirm "Add both lock rules now?"; then
  wrangler r2 bucket lock add "$R2_BUCKET" ledger-blocks ledger/blocks/ --retention-indefinite
  wrangler r2 bucket lock add "$R2_BUCKET" snapshots snapshots/ --retention-days 400
else
  SKIPPED+=("R2 bucket locks (see README go-live checklist)")
fi
pause "Continue?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "R2: API token for the recorder"
open_url "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
step "Create API token → name it nearpost-recorder."
step "Permissions: Object Read & Write. Scope: 'Apply to specific buckets only' → $R2_BUCKET."
step "Create, then copy the Access Key ID and Secret Access Key (the secret is shown once)."
while true; do
  ask_secret R2_ACCESS_KEY_ID "Access Key ID:"
  ask_secret R2_SECRET_ACCESS_KEY "Secret Access Key:"
  # Write, read back and delete a probe object outside the locked prefixes.
  if check=$(R2_ACCOUNT_ID="$R2_ACCOUNT_ID" R2_ACCESS_KEY_ID="$R2_ACCESS_KEY_ID" \
      R2_SECRET_ACCESS_KEY="$R2_SECRET_ACCESS_KEY" R2_BUCKET="$R2_BUCKET" uv run --no-sync python - 2>&1 <<'PY'
import os
from nearpost.store.r2 import make_client
client = make_client(account_id=os.environ["R2_ACCOUNT_ID"], access_key_id=os.environ["R2_ACCESS_KEY_ID"],
                     secret_access_key=os.environ["R2_SECRET_ACCESS_KEY"])
bucket, key = os.environ["R2_BUCKET"], "setup/wizard-probe.txt"
client.put_object(Bucket=bucket, Key=key, Body=b"ok")
assert client.get_object(Bucket=bucket, Key=key)["Body"].read() == b"ok"
client.delete_object(Bucket=bucket, Key=key)
print("read/write ok")
PY
  ); then say "Token works: $check"; break; fi
  note "$(tail -n 3 <<<"$check")"
  retry_or_skip "R2 API token" || break
done
write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
set_secret R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
set_secret R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "GitHub: Actions secrets"
names=$(gh secret list --json name --jq '.[].name' 2>&1 || true)
for name in ODDS_API_KEY HEALTHCHECKS_PING_KEY R2_ACCOUNT_ID R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY R2_BUCKET; do
  if grep -qx "$name" <<<"$names"; then say "✓ $name"; else warn "missing: $name"; SKIPPED+=("GitHub secret $name"); fi
done
note "Values are never shown; GitHub only lists names."
pause "Continue?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "GitHub: token for the Cloudflare Worker"
say "The Worker triggers the recorder, so it needs a token that can do exactly that."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Name: nearpost-scheduler. Expiration: up to a year (note the date)."
step "Repository access: Only select repositories → $NEARPOST_GITHUB_REPO."
step "Permissions → Repository → Actions: Read and write. Nothing else."
step "Generate token and copy it."
while true; do
  ask_secret WORKER_GITHUB_TOKEN "Paste the token:"
  if workflows=$(GH_TOKEN="$WORKER_GITHUB_TOKEN" gh api "repos/$NEARPOST_GITHUB_REPO/actions/workflows" \
      --jq '.workflows[].path' 2>&1) && grep -q "record.yml" <<<"$workflows"; then
    say "Token can see the record workflow."; break
  fi
  note "$(tail -n 2 <<<"$workflows")"
  retry_or_skip "WORKER_GITHUB_TOKEN" || break
done
ask WORKER_GITHUB_TOKEN_EXPIRES "Token expiry date (YYYY-MM-DD):"
write_env WORKER_GITHUB_TOKEN_EXPIRES "$WORKER_GITHUB_TOKEN_EXPIRES"
warn "Add a calendar reminder a week before $WORKER_GITHUB_TOKEN_EXPIRES: an expired token stops all recording."
note "The token itself is not written to .env; it goes only into the Worker's secret store."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare Worker: KV, deploy, secrets"
if grep -q "REPLACE_WITH_KV_NAMESPACE_ID" worker/wrangler.toml; then
  if confirm "Create the KV namespace the Worker uses for dispatch bookkeeping?"; then
    kv_output=$(wrangler kv namespace create nearpost-scheduler-state 2>&1)
    printf '%s\n' "$kv_output" | sed 's/^/    /'
    kv_id=$(grep -oE '[0-9a-f]{32}' <<<"$kv_output" | head -n 1 || true)
    [[ -n "$kv_id" ]] || ask kv_id "Couldn't read the new namespace id; paste it:"
    sed -i.bak "s|REPLACE_WITH_KV_NAMESPACE_ID|$kv_id|" worker/wrangler.toml && rm worker/wrangler.toml.bak
    say "Wrote the KV namespace id into worker/wrangler.toml."
  else
    SKIPPED+=("KV namespace (worker/wrangler.toml still has the placeholder)")
  fi
fi
if confirm "Deploy the nearpost-scheduler Worker now? Its crons start immediately."; then
  wrangler deploy
  printf '%s' "$WORKER_GITHUB_TOKEN" | wrangler secret put GITHUB_TOKEN
  printf '%s' "$HEALTHCHECKS_PING_KEY" | wrangler secret put HC_PING_KEY
  say "Deployed with secrets. The watchdog reports 'status missing' until the first run below."
else
  SKIPPED+=("Worker deploy and secrets (cd worker && npx wrangler deploy)")
fi

# ── 10 ────────────────────────────────────────────────────────────────────
stage "First run"
say "One manual daily run proves every secret and source end to end."
if confirm "Start the record workflow with mode=daily now?"; then
  gh workflow run record.yml -f mode=daily
  sleep 8
  run_id=$(gh run list --workflow record.yml --event workflow_dispatch --limit 1 --json databaseId --jq '.[0].databaseId')
  if gh run watch "$run_id" --exit-status; then
    say "First daily run succeeded."
  else
    warn "The run failed; its log: gh run view $run_id --log-failed"
    SKIPPED+=("a successful first daily run")
  fi
else
  SKIPPED+=("first run (gh workflow run record.yml -f mode=daily)")
fi
pause "Continue?"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "healthchecks.io: schedules and phone alerts"
open_url "https://healthchecks.io/projects/"
step "nearpost-daily: Period 1 day, Grace 3 hours."
step "nearpost-watchdog (appears within ~5 min of deploy): Period 5 minutes, Grace 15 minutes."
step "nearpost-tick (appears after the first tick): Period 7 days, Grace 1 day. It runs on demand;"
step "  its explicit failure pings are what matter."
step "Integrations → add ntfy (phone push) and/or email, and enable them on all three checks."
say "Watch for nearpost-watchdog to turn green: that means the Worker, R2 and status file are live."
pause "Done?"

finish
say "Next: delete the WORKER_GITHUB_TOKEN line from .env if you put one there."
say "Captures begin by themselves when each window opens (GW6 T-7d: 2026-10-03 11:30 UTC)."
